"""Persist synthetic lifecycles generated by ``app.data.generator`` into
the database. Runs the deterministic control engine over every lifecycle
immediately after insertion so that every persisted transaction already
has a resolved status, exception_type, financial_exposure and a
corresponding ExceptionRecord row (if anomalous).

Call ``seed_database()`` once at startup (or via the CLI) to populate
the database for demo / benchmark runs.

PostgreSQL / Supabase notes
---------------------------
Supabase may close idle connections during a long seeding run.  To work
around this we:

1. Use ``db.flush()`` + eager selectinload instead of lazy ORM attribute
   access, reducing the per-transaction round-trips from N+1 to 2.
2. Commit in small batches (50) so each batch gets a fresh connection on
   the next round.
3. Open a brand-new session for each batch so a dropped connection is
   recovered transparently by the pool.
"""
from __future__ import annotations

import logging
from typing import List, Optional

from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.anomaly.classifier import classify_exception
from app.anomaly.severity import classify_severity
from app.audit.logger import log_action
from app.data.generator import SyntheticLifecycle, generate_lifecycles
from app.finance.control_engine import run_controls
from app.finance.exposure import compute_financial_exposure
from app.finance.lifecycle_builder import build_bundle
from app.models.exception import ExceptionRecord
from app.models.transaction import (
    BankEntry,
    Order,
    Payment,
    Refund,
    Settlement,
    Transaction,
    TransactionStatus,
)

logger = logging.getLogger(__name__)


def _get_settings():
    """Deferred settings access — always reads the live cached value."""
    from app.core.config import get_settings as _gs
    return _gs()


def _get_session_factory():
    from app.core.database import SessionLocal
    return SessionLocal


# ---------------------------------------------------------------------------
# Persist one lifecycle (no commit)
# ---------------------------------------------------------------------------

def _persist_lifecycle(db: Session, lc: SyntheticLifecycle) -> Transaction:
    """Write one synthetic lifecycle as ORM rows. Does NOT commit."""

    txn = Transaction(
        transaction_id=lc.transaction_id,
        currency="INR",
        ground_truth_type=lc.ground_truth_type,
        ground_truth_is_anomaly=lc.ground_truth_is_anomaly,
        status=TransactionStatus.PENDING,
    )
    db.add(txn)

    order = lc.order
    db.add(
        Order(
            order_id=order.id,
            transaction_id=lc.transaction_id,
            amount=order.amount,
            created_at=order.timestamp,
        )
    )

    for p in lc.payments:
        db.add(
            Payment(
                payment_id=p.id,
                transaction_id=lc.transaction_id,
                order_id=order.id if not p.is_orphan else None,
                amount=p.amount,
                status="captured",
                payment_timestamp=p.timestamp,
                is_orphan=p.is_orphan,
            )
        )

    for r in lc.refunds:
        primary_pay = next((p for p in lc.payments if not p.is_orphan), None)
        db.add(
            Refund(
                refund_id=r.id,
                transaction_id=lc.transaction_id,
                payment_id=primary_pay.id if primary_pay else None,
                amount=r.amount,
                status="processed",
                refund_timestamp=r.timestamp,
            )
        )

    for s in lc.settlements:
        primary_pay = next((p for p in lc.payments if not p.is_orphan), None)
        db.add(
            Settlement(
                settlement_id=s.id,
                transaction_id=lc.transaction_id,
                payment_id=primary_pay.id if primary_pay else None,
                fee_amount=s.extra.get("fee", 0),
                tax_amount=s.extra.get("tax", 0),
                expected_settlement=s.extra.get("expected", s.amount),
                actual_settlement=s.amount,
                settlement_timestamp=s.timestamp,
                is_orphan=s.is_orphan,
            )
        )

    for b in lc.bank_entries:
        primary_set = next((s for s in lc.settlements if not s.is_orphan), None)
        db.add(
            BankEntry(
                bank_entry_id=b.id,
                transaction_id=lc.transaction_id,
                settlement_id=primary_set.id if primary_set else None,
                amount=b.amount,
                bank_timestamp=b.timestamp,
                is_orphan=b.is_orphan,
            )
        )

    return txn


# ---------------------------------------------------------------------------
# Evaluate one persisted transaction (eager load, no lazy selects)
# ---------------------------------------------------------------------------

def _evaluate_transaction(db: Session, txn: Transaction) -> None:
    """Run control checks on a freshly persisted transaction.

    Reloads ``txn`` with all relationships eagerly loaded in a single query,
    avoiding the N+1 lazy-load round-trips that kept the connection open
    too long on Supabase.
    """
    db.flush()  # materialise pending INSERTs so the SELECT below sees them

    # Re-fetch with all relationships in one JOIN query
    stmt = (
        select(Transaction)
        .options(
            selectinload(Transaction.order),
            selectinload(Transaction.payments),
            selectinload(Transaction.refunds),
            selectinload(Transaction.settlements),
            selectinload(Transaction.bank_entries),
        )
        .where(Transaction.transaction_id == txn.transaction_id)
    )
    loaded_txn = db.execute(stmt).scalar_one()

    bundle = build_bundle(loaded_txn)
    control = run_controls(bundle)
    exception_type = classify_exception(control)
    exposure = compute_financial_exposure(bundle, control, exception_type)

    if exception_type:
        loaded_txn.status = TransactionStatus.EXCEPTION
        loaded_txn.exception_type = exception_type
        loaded_txn.financial_exposure = exposure

        severity = classify_severity(exception_type, exposure)
        exc_record = ExceptionRecord(
            transaction_id=loaded_txn.transaction_id,
            exception_type=exception_type,
            severity=severity,
            financial_exposure=exposure,
            control_evidence=control.evidence(),
            ground_truth_type=loaded_txn.ground_truth_type,
        )
        db.add(exc_record)
        log_action(
            db,
            action="exception_detected",
            transaction_id=loaded_txn.transaction_id,
            message=f"{exception_type} | severity={severity} | exposure={exposure}",
        )
    else:
        loaded_txn.status = TransactionStatus.HEALTHY
        log_action(
            db,
            action="transaction_healthy",
            transaction_id=loaded_txn.transaction_id,
            message="All controls passed.",
        )


# ---------------------------------------------------------------------------
# Clear helpers
# ---------------------------------------------------------------------------

def _clear_all_data(db: Session) -> None:
    """Delete every row from all lifecycle/exception tables.

    PostgreSQL:
        Uses a single ``TRUNCATE … CASCADE`` statement — atomic, no FK
        ordering required, no intermediate commit.  The caller owns the
        transaction boundary.

    SQLite:
        Issues ordered ``DELETE FROM`` statements (TRUNCATE is not
        supported).  Again, no intermediate commit.
    """
    from sqlalchemy import text

    # Detect from the session's actual bind (handles test SQLite overrides)
    bind = db.get_bind()
    is_postgresql = bind.dialect.name == "postgresql"

    if is_postgresql:
        tables_csv = (
            "audit_logs, investigations, exceptions, "
            "bank_entries, settlements, refunds, payments, orders, transactions"
        )
        try:
            db.execute(text(f"TRUNCATE TABLE {tables_csv} RESTART IDENTITY CASCADE"))
            logger.info("All existing data cleared via TRUNCATE CASCADE.")
            return
        except Exception as exc:
            logger.warning("TRUNCATE failed (%s); falling back to ordered DELETEs.", exc)

    _delete_ordered(db)


def _delete_ordered(db: Session) -> None:
    """Ordered DELETE — used for SQLite and as PostgreSQL fallback."""
    from sqlalchemy import text

    tables_in_order = [
        "audit_logs",
        "investigations",
        "exceptions",
        "bank_entries",
        "settlements",
        "refunds",
        "payments",
        "orders",
        "transactions",
    ]
    for table in tables_in_order:
        try:
            db.execute(text(f"DELETE FROM {table}"))
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def seed_database(
    db: Session,
    count: Optional[int] = None,
    seed: Optional[int] = None,
    force: bool = False,
) -> int:
    """Generate and persist synthetic data.

    Args:
        db:    Active SQLAlchemy session.  For PostgreSQL the seeder opens
               its own short-lived per-batch sessions internally, but uses
               ``db`` for the initial existence check and the final count.
        count: Number of lifecycles to generate.  Defaults to the
               ``SYNTHETIC_RECORD_COUNT`` env-var (never hardcoded).
        seed:  RNG seed.  Defaults to ``SYNTHETIC_SEED`` env-var.
        force: Clear all existing data before seeding when True.

    Returns:
        Number of transaction rows inserted (0 if skipped).
    """
    from sqlalchemy import text
    from sqlalchemy.exc import OperationalError
    from app.core.database import init_db, engine as _module_engine

    # Detect the dialect from the session's *actual* bind so that tests
    # that inject an in-memory SQLite session are handled correctly even
    # when the module-level engine points at PostgreSQL.
    bind = db.get_bind()
    is_postgresql = bind.dialect.name == "postgresql"

    # Only call init_db() when using the module-level engine.
    # Test harnesses that inject their own SQLite session manage their own
    # table creation and must not trigger DDL against the remote Supabase DB.
    if bind.url == _module_engine.url:
        init_db()

    try:
        existing = db.execute(text("SELECT COUNT(*) FROM transactions")).scalar() or 0
    except OperationalError:
        existing = 0

    if existing > 0 and not force:
        logger.info("Database already seeded (%d transactions). Skipping.", existing)
        return 0

    if existing > 0 and force:
        logger.info("force=True: clearing %d existing rows before re-seeding…", existing)
        _clear_all_data(db)
        db.flush()

    # Resolve from args → settings (never hardcoded)
    n = count if count is not None else _settings.synthetic_record_count
    s = seed  if seed  is not None else _settings.synthetic_seed

    logger.info("Seeding database with %d synthetic transactions (seed=%d)…", n, s)
    lifecycles: List[SyntheticLifecycle] = generate_lifecycles(n, s)

    # -----------------------------------------------------------------------
    # For PostgreSQL (Supabase): open a fresh session per batch so that a
    # dropped connection is recovered automatically.  Each batch is fully
    # self-contained (insert + evaluate + commit).
    #
    # For SQLite: use the caller's session throughout (connection pooling
    # is not relevant for a local file).
    # -----------------------------------------------------------------------
    batch_size = 50
    inserted = 0
    total_batches = (n + batch_size - 1) // batch_size

    for batch_idx in range(total_batches):
        start = batch_idx * batch_size
        end   = min(start + batch_size, n)
        batch = lifecycles[start:end]

        if is_postgresql:
            # Fresh session per batch → fresh connection from pool
            batch_db = SessionLocal()
        else:
            batch_db = db

        try:
            for lc in batch:
                txn = _persist_lifecycle(batch_db, lc)
                _evaluate_transaction(batch_db, txn)
                inserted += 1

            batch_db.commit()
            logger.info(
                "  …committed batch %d/%d (%d/%d transactions)",
                batch_idx + 1, total_batches, inserted, n,
            )
        except Exception as exc:
            batch_db.rollback()
            logger.error(
                "Batch %d failed: %s — rolling back and aborting.",
                batch_idx + 1, exc,
            )
            if is_postgresql:
                batch_db.close()
            raise
        finally:
            if is_postgresql:
                batch_db.close()

    logger.info("Seeding complete. %d transactions inserted.", inserted)
    return inserted
